#!/bin/bash

SIMILARITY_IMMO=$(compare -metric PSNR ~/Desktop/automator/immoScoutPrevious.png ~/Desktop/automator/immoScout.png ~/Desktop/automator/diff.png 2>&1)

if [[ $SIMILARITY_IMMO = 'inf' || $SIMILARITY_IMMO > '30' ]] 
then 
    say gleich
elif [[ $SIMILARITY_IMMO < '30' ]] 
then
    say Immo Scout
    exit 1
else 
    say $SIMILARITY_IMMO
fi

SIMILARITY_EBAY=$(compare -metric PSNR ~/Desktop/automator/ebayPrevious.png ~/Desktop/automator/ebay.png ~/Desktop/automator/diff.png 2>&1)

SIMILARITY_EBAY_PRE=$(compare -metric PSNR ~/Desktop/automator/ebayPreviousPre.png ~/Desktop/automator/ebay.png ~/Desktop/automator/diff.png 2>&1)

if [[ $SIMILARITY_EBAY = 'inf' || SIMILARITY_EBAY_PRE = 'inf' || $SIMILARITY_EBAY > '20' || SIMILARITY_EBAY_PRE > '20' ]] 
then 
    say gleich
else 
    say ebay
    exit 1 
fi

SIMILARITY_IMMO_WELT=$(compare -metric PSNR ~/Desktop/automator/immoWeltPrevious.png ~/Desktop/automator/immoWelt.png ~/Desktop/automator/diff.png 2>&1)

if [[ $SIMILARITY_IMMO_WELT = 'inf' || $SIMILARITY_IMMO_WELT > '20' ]] 
then 
    say gleich
elif [[ $SIMILARITY_IMMO_WELT < '20' ]] 
then
    say Immo Welt
    exit 1
else 
    say $SIMILARITY_IMMO_WELT
fi

SIMILARITY_IMMO_NET=$(compare -metric PSNR ~/Desktop/automator/immoNetPrevious.png ~/Desktop/automator/immoNet.png ~/Desktop/automator/diff.png 2>&1)

if [[ $SIMILARITY_IMMO_NET = 'inf' || $SIMILARITY_IMMO_NET > '25' ]] 
then 
    say gleich
elif [[ $SIMILARITY_IMMO_NET < '25' ]] 
then
    say Immo Net
    exit 1
else 
    say $SIMILARITY_IMMO_NET
fi